config/routes.rb
Bootstrapuser::Application.routes.draw do
  devise_for :users
  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Hello World</h1>

app/views/layouts/_user.haml
%nav
  .logo= link_to 'Home', root_path, class: "logo"
  .logged_in_name= "Logged in as #{current_user.email}" if current_user
  %span{class: "right_side_nav_links"}
    - if current_user
      = link_to('Logout', destroy_user_session_path, :method => :delete)
    - else
      = form_tag user_session_path do
        Log In
        = text_field_tag 'user[email]', nil,  :placeholder => 'E-Mail'
        = password_field_tag 'user[password]', nil, placeholder: 'Password'
        %button Sign in
        = check_box_tag 'user[remember_me]'
        = label_tag 'user[remember_me]', 'Remember me'
        %span.lost_password
          = link_to "Password lost?", new_password_path('user')
          = link_to "Create Account", new_user_registration_path

app/views/layouts/_user.html.erb
<nav>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<span class="icon-bar"></span>
			<div class="brand">
				<%= link_to "home", root_path %>
			</div>
			<% if current_user %>
			<%= "#{current_user.email}" %>
			<% end %>
			<% if user_signed_in? %>
			<!-- Signed in as <%# current_user.email %>. Not you? -->
			<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
			<% else %>
			<%= link_to "Create Account", new_user_registration_path %>
			<div class="navbar-form pull-right">
				<%= form_tag user_session_path do %>
				<div class="form-control">
					<%= text_field_tag 'user[email]', nil, :placeholder => 'email' %>
					<%= password_field_tag 'user[password]', nil, :placeholder => 'password' %>
					<%= button_tag "sign in" %>
					

				<div class="span2">
					<%= label_tag 'user[remember_me]', 'Remember Me' %>
					<%= check_box_tag 'user[remember_me]' %>
					</div>
					<%= link_to "Password Lost?", new_password_path('user') %>
					</div>
				</div>
				<% end %>
				<% end %>
			</div>
		</div>
	</nav>

app/views/layouts/_user_nav.html.erb
<div id="user_nav">
	<%= link_to "home", root_path %>	
	<% if user_signed_in? %>
		Signed in as <%= current_user.email %>. Not you?
		<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	<% else %>
	<% form_tag user_session_path do %>
		<%= text_field_tag 'user[email]', nil, :placeholder => 'email' %>
		<%= password_field_tag 'user[password]', nil, :placeholder => 'password' %>
		<%= button_tag "sign in" %>
		<%= label_tag 'user[remember_me]', 'Remember Me' %>
		<%= link_to "Password Lost?", new_password_path('user') %>
	<% end %>
<% end %>
</div>

app/views/layouts/_userold.haml
%navbar
  .navbar
    .navbar-brand= link_to 'Home', root_path
    .logged_in_name= "Logged in as #{current_user.email}" if current_user
    %span{class: "right_side_nav_links"}
      - if current_user
        = link_to('Logout', destroy_user_session_path, :method => :delete)
      - else
        = form_tag user_session_path do
          Log In
          = text_field_tag 'user[email]', nil,  :placeholder => 'E-Mail'
          = password_field_tag 'user[password]', nil, placeholder: 'Password'
          %button Sign in
          = check_box_tag 'user[remember_me]'
          = label_tag 'user[remember_me]', 'Remember me'
          %span.lost_password
            = link_to "Password lost?", new_password_path('user')
            = link_to "Create Account", new_user_registration_path
            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Bootstrap Custom User Login Template</title>
	 <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="container">
		<div class="row">
		  <%= render "/layouts/user" %></div>
  <div class="span12">
		<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

		<%= yield %>
    </div>
	</div>
</body>
</html>